sudo: false

language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"

install:
- pip install -e .
- pip install coverage pep8 pyflakes mock

script:
- pyflakes argsrun tests
- pep8 argsrun tests
- python -m unittest discover -v tests
