sudo: false

language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"

cache:
  directories:
  - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
- pip install coverage pep8 pyflakes mock
- python setup.py develop

script:
- pyflakes argsrun tests
- pep8 argsrun tests
- python -m unittest discover -v tests
